name: Build pylibqrencode on Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Build DLL and Test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSVC Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1

    - name: Install vcpkg and build libqrencode
      shell: cmd
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg install libqrencode

    - name: Compile qrpng_wrapper.c into qrpng.dll
      shell: cmd
      run: |
        cl qrpng_wrapper.c /LD ^
          /I"vcpkg\installed\x64-windows\include" ^
          /link /OUT:pylibqrencode\qrpng.dll ^
          vcpkg\installed\x64-windows\lib\qrencode.lib

    - name: Test QR code generation with Python
      shell: cmd
      run: |
        pip install pillow
        python -c "from pylibqrencode import generate_qr; generate_qr(b'GitHub Actions', scale=4).save('test_qr.png')"

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: qrpng-dll
        path: pylibqrencode/qrpng.dll
